# 
#
#
name: share

services:
  samba-server:
    container_name: samba-server
    configs:
      - source: samba_config
        target: /etc/smb/smb.conf
        mode: 0440

    image: ghcr.io/sipopo/samba:latest
    volumes:
      - ${SHARE_LOCATION}:/share
    env_file:
      - .env
    ports:
      - '445:445'
    networks:
      - host

configs:
  samba_config:
    file: ./smb.conf

networks:
  host:


